# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: os-shell
      image: sealos.hub:5000/kube4/os-shell:12-r1
    - name: rabbitmq
      image: sealos.hub:5000/kube4/rabbitmq:4.3.6-r1
  licenses: Apache-2.0
  archinfra.io/upstream-chart: bitnami/rabbitmq@16.0.16
  archinfra.io/runtime-contract: bitnami-rabbitmq-runtime-v1
apiVersion: v2
appVersion: 4.3.6
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Archinfra-maintained RabbitMQ Cluster chart fork for offline production delivery.
home: https://github.com/archinfra/apps_rabbitmq-cluster
keywords:
- rabbitmq
- message queue
- AMQP
maintainers:
- name: archinfra
  url: https://github.com/archinfra
name: rabbitmq
sources:
- https://github.com/archinfra/apps_rabbitmq-cluster
- https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq
version: 16.0.16-archinfra.1
